name: Conv3D
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.15.4
  - pip=19.0.1
  - python=3.6.8
  - pytorch=1.0.1=py3.6_cuda9.0.176_cudnn7.4.2_2
  - scipy=1.2.0
  - tensorboard=1.12.2




